import sys
import pandas as pd

"""
Compute the primary base composition of variable blocks from a block
annotation table (produced by parse_alignment_by_blocks.py).

DEFINITIONS
------
Primary bases: The smallest set of bases (A,C,G,T) whose combined frequency is >= 0.75.
    
NOTES
------
- Coordinates are 0-based and inclusive.

USAGE
------
python count_blocks_primary_bases.py <blocks.tsv> <output.tsv> <block_length_threshold>
    
ARGUMENTS
-------
<blocks.tsv> : A TSV file containing start, end, type, A_count, C_count, G_count, T_count (e.g. generated by parse_alignment_by_blocks.py).
<output.tsv> : Output TSV file path.

"""

if len(sys.argv) < 3:
    print("Usage: python count_blocks_primary_bases.py <blocks.tsv> <output.tsv>")
    sys.exit(1)

df = pd.read_csv(sys.argv[1], sep='\t')

output_file = open(sys.argv[2], "w")
output_file.write("length\tprimary_bases\n")

THRESHOLD = 0.75  # primary bases threshold

try:
    LENGTH_THRESHOLD = int(sys.argv[3])
except TypeError:
    print("Block length threshold must be an integer.")
    sys.exit(1)


def get_primary_bases(counts):
    """Return a sorted string of primary bases whose cumulative frequency >= THRESHOLD."""
    total = sum(counts.values())
    if total == 0:
        return "no base -> NOT VALID LINE"

    # sort bases from most to the least frequent
    sorted_bases = sorted(counts.items(), key=lambda x: x[1], reverse=True)

    cumulative = 0.0
    primary = []

    for base, count in sorted_bases:
        perc = count / total
        if perc == 0:
            continue
        primary.append(base.upper())
        cumulative += perc
        if cumulative >= THRESHOLD:
            break

    return ''.join(primary)


for _, row in df.iterrows():
    if row['type'] == 'variable':
        counts = {
            'A': int(row.get('A_count', 0)),
            'C': int(row.get('C_count', 0)),
            'G': int(row.get('G_count', 0)),
            'T': int(row.get('T_count', 0)),
        }

        primary_bases = get_primary_bases(counts)
        primary_bases = ''.join(sorted(primary_bases))
        length = int(row['end']) - int(row['start']) + 1
        if length >= LENGTH_THRESHOLD:
            output_file.write(f"{length}\t{primary_bases}\n")

output_file.close()
print(f"Primary bases written to {sys.argv[2]}")